<?php

function cropit_menu(){

/*
  $items['admin/config/cropit'] = array(
      'title' => 'Cropit',
      'description' => 'Configuration for Cropit module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cropit_admin_form'),
      'access arguments' => array('administer cropit'),
      'type' => MENU_NORMAL_ITEM,
    );
  $items['admin/config/cropit/settings'] = array(
      'title' => 'Cropit settings',
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );*/

  $items['cropit/save_image'] = array(

      'title' => 'Cropit',
      'description' => 'Configuration for Cropit module',
      'page callback' => 'cropit_save_file_from_datauri',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,

    );


  return $items;

}

function cropit_save_file_from_datauri(){

// SECURITY!!!!!
  $encodedData = $_POST['data_uri'];

  $encodedData = substr($encodedData,strpos($encodedData,",")+1);

  $encodedData = str_replace(' ','+',$encodedData);
  $decodedData = base64_decode($encodedData);

  $files_path = variable_get('file_public_path', conf_path() . '/files');

  $img_path = $files_path . '/test2.jpg';

  $bytes = file_put_contents($img_path, $decodedData);

  if($bytes){
    print '<img src="' . $img_path . '" />' . $img_path;

  }else{
    print 'faiiiil';
  }

  die();

}

function cropit_field_widget_info() {
  return array(
    'image_cropit' => array(
      'label' => t('Cropit'),
      'field types' => array('image'),
      'settings' => array(),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

function cropit_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  drupal_set_message($instance['widget']['type']);
  $element += array(
    '#type' => $instance['widget']['type'],
    '#default_value' => isset($items[$delta]) ? $items[$delta] : '',
  );
  return array('value' => $element);
}

function cropit_field_widget_form_alter(&$element, &$form_state, $context){

  //drupal_set_message(print_r($element,true));
  drupal_add_js('/sites/all/libraries/cropit/dist/jquery.cropit.min.js');


  drupal_add_css(drupal_get_path('module','cropit') . '/cropit.css');

  drupal_add_js(drupal_get_path('module','cropit') . '/cropit.js');

}